syntax = "proto3";
option go_package = "./cemm";
import "google/protobuf/empty.proto";
package CEMM;

service CEMM {


  rpc get (GetRequest) returns ( stream GetReply) {}
  rpc add (AddRequest) returns ( google.protobuf.Empty ) {}
  rpc addRound (google.protobuf.Empty) returns (AddRoundReply) {}
  rpc searchRound (google.protobuf.Empty) returns (SearchRoundReply) {}
  rpc init(stream InitRequest) returns (google.protobuf.Empty) {}

}

message AddToken
{
  bytes addr =1;
  bytes node =2;
}

message InitRequest
{
  repeated AddToken nodes =1;
}

message GetRequest
{
  bytes tw =1;
  repeated bytes sts =2;
  int64 vs =3;
}

message GetReply
{
  bytes node =1;
}


message AddRequest
{
  AddToken newNode =1;
  AddToken srchNode =2;
}


message AddRoundReply
{
  int64 round =1;
}

message SearchRoundReply
{
  int64 round =1;
  int64 vs =2;
}