// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: CEMM.proto

package cemm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          []byte                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Node          []byte                 `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToken) Reset() {
	*x = AddToken{}
	mi := &file_CEMM_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToken) ProtoMessage() {}

func (x *AddToken) ProtoReflect() protoreflect.Message {
	mi := &file_CEMM_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToken.ProtoReflect.Descriptor instead.
func (*AddToken) Descriptor() ([]byte, []int) {
	return file_CEMM_proto_rawDescGZIP(), []int{0}
}

func (x *AddToken) GetAddr() []byte {
	if x != nil {
		return x.Addr
	}
	return nil
}

func (x *AddToken) GetNode() []byte {
	if x != nil {
		return x.Node
	}
	return nil
}

type InitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*AddToken            `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_CEMM_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_CEMM_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_CEMM_proto_rawDescGZIP(), []int{1}
}

func (x *InitRequest) GetNodes() []*AddToken {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tw            []byte                 `protobuf:"bytes,1,opt,name=tw,proto3" json:"tw,omitempty"`
	Sts           [][]byte               `protobuf:"bytes,2,rep,name=sts,proto3" json:"sts,omitempty"`
	Vs            int64                  `protobuf:"varint,3,opt,name=vs,proto3" json:"vs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_CEMM_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_CEMM_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_CEMM_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetTw() []byte {
	if x != nil {
		return x.Tw
	}
	return nil
}

func (x *GetRequest) GetSts() [][]byte {
	if x != nil {
		return x.Sts
	}
	return nil
}

func (x *GetRequest) GetVs() int64 {
	if x != nil {
		return x.Vs
	}
	return 0
}

type GetReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          []byte                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReply) Reset() {
	*x = GetReply{}
	mi := &file_CEMM_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReply) ProtoMessage() {}

func (x *GetReply) ProtoReflect() protoreflect.Message {
	mi := &file_CEMM_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReply.ProtoReflect.Descriptor instead.
func (*GetReply) Descriptor() ([]byte, []int) {
	return file_CEMM_proto_rawDescGZIP(), []int{3}
}

func (x *GetReply) GetNode() []byte {
	if x != nil {
		return x.Node
	}
	return nil
}

type AddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewNode       *AddToken              `protobuf:"bytes,1,opt,name=newNode,proto3" json:"newNode,omitempty"`
	SrchNode      *AddToken              `protobuf:"bytes,2,opt,name=srchNode,proto3" json:"srchNode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRequest) Reset() {
	*x = AddRequest{}
	mi := &file_CEMM_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRequest) ProtoMessage() {}

func (x *AddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_CEMM_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRequest.ProtoReflect.Descriptor instead.
func (*AddRequest) Descriptor() ([]byte, []int) {
	return file_CEMM_proto_rawDescGZIP(), []int{4}
}

func (x *AddRequest) GetNewNode() *AddToken {
	if x != nil {
		return x.NewNode
	}
	return nil
}

func (x *AddRequest) GetSrchNode() *AddToken {
	if x != nil {
		return x.SrchNode
	}
	return nil
}

type AddRoundReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Round         int64                  `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRoundReply) Reset() {
	*x = AddRoundReply{}
	mi := &file_CEMM_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRoundReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRoundReply) ProtoMessage() {}

func (x *AddRoundReply) ProtoReflect() protoreflect.Message {
	mi := &file_CEMM_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRoundReply.ProtoReflect.Descriptor instead.
func (*AddRoundReply) Descriptor() ([]byte, []int) {
	return file_CEMM_proto_rawDescGZIP(), []int{5}
}

func (x *AddRoundReply) GetRound() int64 {
	if x != nil {
		return x.Round
	}
	return 0
}

type SearchRoundReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Round         int64                  `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	Vs            int64                  `protobuf:"varint,2,opt,name=vs,proto3" json:"vs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRoundReply) Reset() {
	*x = SearchRoundReply{}
	mi := &file_CEMM_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRoundReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRoundReply) ProtoMessage() {}

func (x *SearchRoundReply) ProtoReflect() protoreflect.Message {
	mi := &file_CEMM_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRoundReply.ProtoReflect.Descriptor instead.
func (*SearchRoundReply) Descriptor() ([]byte, []int) {
	return file_CEMM_proto_rawDescGZIP(), []int{6}
}

func (x *SearchRoundReply) GetRound() int64 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *SearchRoundReply) GetVs() int64 {
	if x != nil {
		return x.Vs
	}
	return 0
}

var File_CEMM_proto protoreflect.FileDescriptor

var file_CEMM_proto_rawDesc = string([]byte{
	0x0a, 0x0a, 0x43, 0x45, 0x4d, 0x4d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x43, 0x45,
	0x4d, 0x4d, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x32, 0x0a, 0x08, 0x41, 0x64, 0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x61,
	0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x6e,
	0x6f, 0x64, 0x65, 0x22, 0x33, 0x0a, 0x0b, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x24, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x43, 0x45, 0x4d, 0x4d, 0x2e, 0x41, 0x64, 0x64, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x22, 0x3e, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x77, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x02, 0x74, 0x77, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x74, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0c, 0x52, 0x03, 0x73, 0x74, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x76, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x76, 0x73, 0x22, 0x1e, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x22, 0x62, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x07, 0x6e, 0x65, 0x77, 0x4e, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x43, 0x45, 0x4d, 0x4d, 0x2e, 0x41,
	0x64, 0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x07, 0x6e, 0x65, 0x77, 0x4e, 0x6f, 0x64, 0x65,
	0x12, 0x2a, 0x0a, 0x08, 0x73, 0x72, 0x63, 0x68, 0x4e, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x43, 0x45, 0x4d, 0x4d, 0x2e, 0x41, 0x64, 0x64, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x52, 0x08, 0x73, 0x72, 0x63, 0x68, 0x4e, 0x6f, 0x64, 0x65, 0x22, 0x25, 0x0a, 0x0d,
	0x41, 0x64, 0x64, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x72, 0x6f,
	0x75, 0x6e, 0x64, 0x22, 0x38, 0x0a, 0x10, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x6f, 0x75,
	0x6e, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x0e, 0x0a,
	0x02, 0x76, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x76, 0x73, 0x32, 0x99, 0x02,
	0x0a, 0x04, 0x43, 0x45, 0x4d, 0x4d, 0x12, 0x2b, 0x0a, 0x03, 0x67, 0x65, 0x74, 0x12, 0x10, 0x2e,
	0x43, 0x45, 0x4d, 0x4d, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x0e, 0x2e, 0x43, 0x45, 0x4d, 0x4d, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x00, 0x30, 0x01, 0x12, 0x31, 0x0a, 0x03, 0x61, 0x64, 0x64, 0x12, 0x10, 0x2e, 0x43, 0x45, 0x4d,
	0x4d, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x08, 0x61, 0x64, 0x64, 0x52, 0x6f, 0x75,
	0x6e, 0x64, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x13, 0x2e, 0x43, 0x45, 0x4d,
	0x4d, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x00, 0x12, 0x3f, 0x0a, 0x0b, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x6f, 0x75, 0x6e, 0x64,
	0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16, 0x2e, 0x43, 0x45, 0x4d, 0x4d, 0x2e,
	0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x00, 0x12, 0x35, 0x0a, 0x04, 0x69, 0x6e, 0x69, 0x74, 0x12, 0x11, 0x2e, 0x43, 0x45, 0x4d,
	0x4d, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x28, 0x01, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x63,
	0x65, 0x6d, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_CEMM_proto_rawDescOnce sync.Once
	file_CEMM_proto_rawDescData []byte
)

func file_CEMM_proto_rawDescGZIP() []byte {
	file_CEMM_proto_rawDescOnce.Do(func() {
		file_CEMM_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_CEMM_proto_rawDesc), len(file_CEMM_proto_rawDesc)))
	})
	return file_CEMM_proto_rawDescData
}

var file_CEMM_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_CEMM_proto_goTypes = []any{
	(*AddToken)(nil),         // 0: CEMM.AddToken
	(*InitRequest)(nil),      // 1: CEMM.InitRequest
	(*GetRequest)(nil),       // 2: CEMM.GetRequest
	(*GetReply)(nil),         // 3: CEMM.GetReply
	(*AddRequest)(nil),       // 4: CEMM.AddRequest
	(*AddRoundReply)(nil),    // 5: CEMM.AddRoundReply
	(*SearchRoundReply)(nil), // 6: CEMM.SearchRoundReply
	(*emptypb.Empty)(nil),    // 7: google.protobuf.Empty
}
var file_CEMM_proto_depIdxs = []int32{
	0, // 0: CEMM.InitRequest.nodes:type_name -> CEMM.AddToken
	0, // 1: CEMM.AddRequest.newNode:type_name -> CEMM.AddToken
	0, // 2: CEMM.AddRequest.srchNode:type_name -> CEMM.AddToken
	2, // 3: CEMM.CEMM.get:input_type -> CEMM.GetRequest
	4, // 4: CEMM.CEMM.add:input_type -> CEMM.AddRequest
	7, // 5: CEMM.CEMM.addRound:input_type -> google.protobuf.Empty
	7, // 6: CEMM.CEMM.searchRound:input_type -> google.protobuf.Empty
	1, // 7: CEMM.CEMM.init:input_type -> CEMM.InitRequest
	3, // 8: CEMM.CEMM.get:output_type -> CEMM.GetReply
	7, // 9: CEMM.CEMM.add:output_type -> google.protobuf.Empty
	5, // 10: CEMM.CEMM.addRound:output_type -> CEMM.AddRoundReply
	6, // 11: CEMM.CEMM.searchRound:output_type -> CEMM.SearchRoundReply
	7, // 12: CEMM.CEMM.init:output_type -> google.protobuf.Empty
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_CEMM_proto_init() }
func file_CEMM_proto_init() {
	if File_CEMM_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_CEMM_proto_rawDesc), len(file_CEMM_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_CEMM_proto_goTypes,
		DependencyIndexes: file_CEMM_proto_depIdxs,
		MessageInfos:      file_CEMM_proto_msgTypes,
	}.Build()
	File_CEMM_proto = out.File
	file_CEMM_proto_goTypes = nil
	file_CEMM_proto_depIdxs = nil
}
